### ISSUE TITLE
Week 3 Vision Subsystem Tasks

### ISSUE THREAD

**Issue by jonathandao0** [4201VitruvianBots/Crescendo2024#55]
- [x] Fix Vision subsystem crashes (Test with running code in simulation)
- [x] Implement PhotonVision Simulation
- [ ] Work on Limelight Note ML detection
- [x] Add Vision Pose Estimations to feed SwerveDriveOdometry

Code References:
- 6995: https://github.com/frc6995/Robot-2023/tree/main

**Comment by Mason-Beard** [comment]
Plan for shooter


[](https://docs.google.com/document/d/1WsPKM2BDTdfWXWErZkLVMk5wY-QrJyFVpz2KYH8OBSY/edit?usp=sharing)
